version: '3'
services:
  ilias:
      image: digitallearningforschools/ilias-school:5.4
      expose:
        - 80
      links:
        - mysql
      volumes:
        - ilias_www:/var/www/html/data
        - ilias_data:/var/iliasdata/ilias
      environment:
        - ILIAS_AUTO_SETUP=${ILIAS_AUTO_SETUP}
        - ILIAS_DB_USER=${ILIAS_DB_USER}
        - ILIAS_DB_PASSWORD=${ILIAS_DB_PASSWORD}
        - ILIAS_HOST_NAME=${ILIAS_HOST_NAME}
        - ILIAS_CLIENT_NAME=${ILIAS_CLIENT_NAME}
        - ILIAS_DB_DUMP=${ILIAS_DB_DUMP}
        - ILIAS_DEFAULT_SKIN=${ILIAS_DEFAULT_SKIN}
        - ILIAS_DEFAULT_STYLE=${ILIAS_DEFAULT_STYLE}
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
  mysql:
      image: mysql:5.7
      command: |
          --character-set-server=utf8
          --collation-server=utf8_general_ci
      volumes:
        - ilias_mysql:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
volumes:
  ilias_www:
  ilias_data:
  ilias_mysql:
networks:
  default:
    external:
        name: elearning
