# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Python static code analysis
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.14.0
      with:
        # How would you like the results to be displayed?
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
    # Shell script static code analysis
    - name: Lint check
      uses: azohra/shell-linter@v0.2.0
      with:
        path: "scripts/backup,scripts/purge,scripts/start,scripts/stop,scripts/update"
